"""empty message

Revision ID: b156544e163c
Revises: d1e6bcab2d2c
Create Date: 2020-08-27 17:04:27.062806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b156544e163c'
down_revision = 'd1e6bcab2d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('upcoming_shows', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'upcoming_shows')
    # ### end Alembic commands ###
